### ISSUE TITLE
Make it so release is properly done with a single command

### ISSUE THREAD

**Issue by cholmes** [cholmes/qgis_plugin_gpq_downloader#71]
Not sure the best option for this, maybe a .toml file and some build system? I'm pretty open here, and this is a really lightweight need as we're not distributing to pypi or anything. Could even just be a little bash script. But we should have some way to generate the .zip release instead of me just remembering the right zip command.

Original comment:

> The release 'process' right now is to have the main repo up to date with the release tag and then just go one directory up and run: ` zip -r qgis_plugin_gpq_downloader.zip qgis_plugin_gpq_downloader/ -x "*.DS_Store" "*.gitignore" "*/.git/*"`
> 
> 
> 
> So making that a command would be a nice step. And then also moving the files so that the plugin is in a folder, instead of the whole repo. 

 _Originally posted by @cholmes in [#18](https://github.com/cholmes/qgis_plugin_gpq_downloader/issues/18#issuecomment-2533424719)_

**Comment by mtravis** [comment]
@cholmes you could use Github Actions to do this. Something like this could work.

```
# .github/workflows/release.yml

name: Build and Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip the plugin
        run: |
          mkdir -p release
          zip -r release/qgis_plugin_gpq_downloader.zip * -x ".git*" ".github*" "release*"  # Exclude unnecessary files

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: qgis-plugin-release
          path: release/qgis_plugin_gpq_downloader.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download zipped plugin
        uses: actions/download-artifact@v3
        with:
          name: qgis-plugin-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: qgis_plugin_gpq_downloader.zip
          body: "Automated release of QGIS plugin for Overture Maps."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

 I can try testing this out tomorrow.
